import {
  // Bangunan & Ruangan
  Building,
  Building2,
  School,
  Home,
  House,
  DoorOpen,
  Warehouse,
  Store,
  Hotel,
  Tent,
  Castle,
  // Komputer & Teknologi
  Monitor,
  MonitorSmartphone,
  Laptop,
  Cpu,
  Server,
  Wifi,
  Printer,
  Smartphone,
  Tablet,
  Keyboard,
  Mouse,
  HardDrive,
  Database,
  Cloud,
  // Sains & Lab
  FlaskConical,
  FlaskRound,
  TestTube,
  TestTube2,
  Microscope,
  Atom,
  Dna,
  Beaker,
  // Olahraga & Kesehatan
  Dumbbell,
  Trophy,
  Medal,
  Target,
  Bike,
  Footprints,
  HeartPulse,
  Activity,
  Swords,
  // Seni & Kreativitas
  Music,
  Music2,
  Music3,
  Music4,
  Palette,
  Pencil,
  PenTool,
  Brush,
  Camera,
  Video,
  Clapperboard,
  Mic,
  Radio,
  Headphones,
  // Akademik & Perpustakaan
  BookOpen,
  Book,
  Library,
  GraduationCap,
  FileText,
  Notebook,
  NotebookPen,
  PenLine,
  Newspaper,
  // Fasilitas Umum
  Coffee,
  Utensils,
  UtensilsCrossed,
  Car,
  Bus,
  Bike as BikeIcon,
  Wrench,
  Hammer,
  Zap,
  Leaf,
  Trees,
  Flower,
  Shield,
  ShieldCheck,
  Users,
  Users2,
  Briefcase,
  Star,
  // Kesehatan
  Stethoscope,
  Pill,
  Heart,
  // Keagamaan
  Church,
  // Komunikasi
  Phone,
  Mail,
  Globe,
  Map,
  MapPin,
  // Lainnya
  Award,
  Package,
  Box,
  Archive,
  ClipboardList,
  Settings,
  Tool,
  Lightbulb,
  Sun,
  Moon,
  Wind,
  Droplets,
  Flame,
  Trash2,
  type LucideIcon,
} from "lucide-react";

export interface IconEntry {
  name: string;
  label: string;
  icon: LucideIcon;
}

export const ICONS: IconEntry[] = [
  // Bangunan & Ruangan
  { name: "Building2", label: "Gedung", icon: Building2 },
  { name: "Building", label: "Bangunan", icon: Building },
  { name: "School", label: "Sekolah", icon: School },
  { name: "Home", label: "Ruangan", icon: Home },
  { name: "House", label: "Rumah", icon: House },
  { name: "DoorOpen", label: "Pintu", icon: DoorOpen },
  { name: "Warehouse", label: "Gudang", icon: Warehouse },
  { name: "Store", label: "Toko", icon: Store },
  { name: "Hotel", label: "Asrama", icon: Hotel },
  { name: "Tent", label: "Kemah", icon: Tent },
  { name: "Castle", label: "Kastil", icon: Castle },
  // Komputer & Teknologi
  { name: "Monitor", label: "Komputer", icon: Monitor },
  { name: "MonitorSmartphone", label: "Multi Layar", icon: MonitorSmartphone },
  { name: "Laptop", label: "Laptop", icon: Laptop },
  { name: "Cpu", label: "CPU", icon: Cpu },
  { name: "Server", label: "Server", icon: Server },
  { name: "Wifi", label: "WiFi", icon: Wifi },
  { name: "Printer", label: "Printer", icon: Printer },
  { name: "Smartphone", label: "Smartphone", icon: Smartphone },
  { name: "Tablet", label: "Tablet", icon: Tablet },
  { name: "Keyboard", label: "Keyboard", icon: Keyboard },
  { name: "Mouse", label: "Mouse", icon: Mouse },
  { name: "HardDrive", label: "Hard Drive", icon: HardDrive },
  { name: "Database", label: "Database", icon: Database },
  { name: "Cloud", label: "Cloud", icon: Cloud },
  // Sains & Lab
  { name: "FlaskConical", label: "Lab Kimia", icon: FlaskConical },
  { name: "FlaskRound", label: "Labu", icon: FlaskRound },
  { name: "TestTube", label: "Lab Sains", icon: TestTube },
  { name: "TestTube2", label: "Tabung Uji", icon: TestTube2 },
  { name: "Microscope", label: "Mikroskop", icon: Microscope },
  { name: "Atom", label: "Fisika", icon: Atom },
  { name: "Dna", label: "Biologi", icon: Dna },
  { name: "Beaker", label: "Kimia", icon: Beaker },
  // Olahraga & Kesehatan
  { name: "Dumbbell", label: "Fitness", icon: Dumbbell },
  { name: "Trophy", label: "Trofi", icon: Trophy },
  { name: "Medal", label: "Medali", icon: Medal },
  { name: "Target", label: "Target", icon: Target },
  { name: "Bike", label: "Sepeda", icon: Bike },
  { name: "Footprints", label: "Lintasan", icon: Footprints },
  { name: "HeartPulse", label: "Kesehatan", icon: HeartPulse },
  { name: "Activity", label: "Aktivitas", icon: Activity },
  { name: "Swords", label: "Bela Diri", icon: Swords },
  // Seni & Kreativitas
  { name: "Music", label: "Musik", icon: Music },
  { name: "Music2", label: "Studio", icon: Music2 },
  { name: "Music3", label: "Not Musik", icon: Music3 },
  { name: "Music4", label: "Nada", icon: Music4 },
  { name: "Palette", label: "Seni Rupa", icon: Palette },
  { name: "Pencil", label: "Menggambar", icon: Pencil },
  { name: "PenTool", label: "Desain", icon: PenTool },
  { name: "Brush", label: "Melukis", icon: Brush },
  { name: "Camera", label: "Fotografi", icon: Camera },
  { name: "Video", label: "Studio Video", icon: Video },
  { name: "Clapperboard", label: "Film", icon: Clapperboard },
  { name: "Mic", label: "Mikrofon", icon: Mic },
  { name: "Radio", label: "Radio", icon: Radio },
  { name: "Headphones", label: "Audio", icon: Headphones },
  // Akademik & Perpustakaan
  { name: "BookOpen", label: "Buku", icon: BookOpen },
  { name: "Book", label: "Buku Teks", icon: Book },
  { name: "Library", label: "Perpustakaan", icon: Library },
  { name: "GraduationCap", label: "Akademik", icon: GraduationCap },
  { name: "FileText", label: "Dokumen", icon: FileText },
  { name: "Notebook", label: "Buku Catatan", icon: Notebook },
  { name: "NotebookPen", label: "Catatan", icon: NotebookPen },
  { name: "PenLine", label: "Menulis", icon: PenLine },
  { name: "Newspaper", label: "Koran", icon: Newspaper },
  // Fasilitas Umum
  { name: "Coffee", label: "Kantin", icon: Coffee },
  { name: "Utensils", label: "Dapur", icon: Utensils },
  { name: "UtensilsCrossed", label: "Kafetaria", icon: UtensilsCrossed },
  { name: "Car", label: "Parkir", icon: Car },
  { name: "Bus", label: "Transportasi", icon: Bus },
  { name: "Wrench", label: "Bengkel", icon: Wrench },
  { name: "Hammer", label: "Workshop", icon: Hammer },
  { name: "Zap", label: "Listrik", icon: Zap },
  { name: "Leaf", label: "Taman", icon: Leaf },
  { name: "Trees", label: "Hutan", icon: Trees },
  { name: "Flower", label: "Kebun", icon: Flower },
  { name: "Shield", label: "Keamanan", icon: Shield },
  { name: "ShieldCheck", label: "Aman", icon: ShieldCheck },
  { name: "Users", label: "Aula", icon: Users },
  { name: "Users2", label: "Komunitas", icon: Users2 },
  { name: "Briefcase", label: "Kantor", icon: Briefcase },
  { name: "Star", label: "Unggulan", icon: Star },
  // Kesehatan
  { name: "Stethoscope", label: "UKS", icon: Stethoscope },
  { name: "Pill", label: "Obat", icon: Pill },
  { name: "Heart", label: "Kesehatan Jiwa", icon: Heart },
  // Keagamaan
  { name: "Church", label: "Ibadah", icon: Church },
  // Komunikasi & Lokasi
  { name: "Phone", label: "Telepon", icon: Phone },
  { name: "Mail", label: "Surat", icon: Mail },
  { name: "Globe", label: "Internet", icon: Globe },
  { name: "Map", label: "Peta", icon: Map },
  { name: "MapPin", label: "Lokasi", icon: MapPin },
  // Lainnya
  { name: "Award", label: "Penghargaan", icon: Award },
  { name: "Package", label: "Paket", icon: Package },
  { name: "Box", label: "Kotak", icon: Box },
  { name: "Archive", label: "Arsip", icon: Archive },
  { name: "ClipboardList", label: "Daftar", icon: ClipboardList },
  { name: "Settings", label: "Pengaturan", icon: Settings },
  { name: "Lightbulb", label: "Ide", icon: Lightbulb },
  { name: "Sun", label: "Sinar", icon: Sun },
  { name: "Moon", label: "Malam", icon: Moon },
  { name: "Wind", label: "Ventilasi", icon: Wind },
  { name: "Droplets", label: "Air", icon: Droplets },
  { name: "Flame", label: "Api", icon: Flame },
  { name: "Trash2", label: "Tempat Sampah", icon: Trash2 },
];

export const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICONS.map((e) => [e.name, e.icon]),
);
